spring:
  datasource:
    url: jdbc:h2:~/test;MODE=MySQL
    username: sa
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: select 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
  h2:
    console:
      enabled: true
